apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: app-one

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: paulbouwer/hello-kubernetes:1
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: MESSAGE
          value: "Hello from app1."
        - name: PORT
          value: "80"
