apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: app-three

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: paulbouwer/hello-kubernetes:1
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: MESSAGE
          value: "Hello from app3."
        - name: PORT
          value: "80"
