# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration version (from Vagrant 1.1 to 2.0.x)
Vagrant.configure("2") do |config|

    # The base image to create the VM
    config.vm.box = "debian/bookworm64"
  
    # Define our VM named "bbrassarS"
    config.vm.define "bbrassarS" do |bbrassarS|
      # Change the hostname to "bbrassarS"
      bbrassarS.vm.hostname = "bbrassarS"
      # Change the IP address to "192.168.56.110"
      bbrassarS.vm.network "private_network", ip: "192.168.56.110"
      # VirtualBox configuration
      bbrassarS.vm.provider "virtualbox" do |v|
        # Change the name to "bbrassarS"
        v.name = "bbrassarS"
        # Allow 2048 MB of RAM
        v.memory = 2048
        # Allow 2 CPU
        v.cpus = 2
      end
      # Copy the file hello-kubernetes-ingress.yaml in the VM 
      bbrassarS.vm.provision "file",
      source: "confs/",
      destination: "$HOME/"
      # Upload and execute the script "master.sh" within the VM
      bbrassarS.vm.provision "shell", path: "scripts/master.sh"
    end
  
  end
  